version: "3"

services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3307:3306

  server:
    container_name: api
    build:
      context: ./server/app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    # depends_on:
    #   - db
    stdin_open: true
    tty: true

  webUI:
    container_name: webUI
    build:
      context: ./webUI
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes:
    - ./webUI/src:/app/src


  admin:
    container_name: admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3001:3001
    volumes:
      - ./admin/src:/app/src
