version: "3"

services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3307:3306

  server:
    container_name: server
    build:
      context: ./server/app_sequelize/api-sequelize
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET_KEY: ${CLOUDINARY_SECRET_KEY}
      CLOUDINARY_URL: ${CLOUDINARY_URL}

    # depends_on:
    #   - db
    stdin_open: true
    tty: true

  webui:
    container_name: webUI
    build:
      context: ./webUI
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_GET_DISHES: ${REACT_APP_GET_DISHES}
    ports:
      - 80:80
    volumes:
    - ./webUI/build:/app/build

  admin:
    container_name: admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3001:3001
    volumes:
      - ./admin/src:/app/src
