version: "3"

services:
  db:
    image: mysql:latest
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysqldb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3307:3306

  server:
    container_name: api
    build:
      context: ./server/app
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: test
      DB_PORT: 3306
    depends_on:
      - db
    stdin_open: true
    tty: true
    # volumes:
    #   - ./server/app:/app/src

  userinterface:
    container_name: WebUserInterface
    build:
      context: ./WebUserInterface
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes:
      - ./WebUserInterface/src:/app/src

  admin:
    container_name: admin
    build:
      context: ./admin
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3001:3001
    volumes:
      - ./admin/src:/app/src
#  nginx:
#    build:
#      context: ./docker/nginx
#      dockerfile: Dockerfile
#    container_name: nginx
#    ports:
#      - 80:80
#    depends_on:
#      - userinterface
#      - server
#      - admin
