version: "3.8"

services:
  db:
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_PORT:$MYSQL_DOCKER_PORT

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    image: zalart/backend_app
    restart: always
    ports:
      - $NODE_PORT:$NODE_DOCKER_PORT
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
      - DB_PORT=$MYSQL_DOCKER_PORT
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
