enum ScreenNames {
  ProfileNavigator = 'ProfileNavigator',
  MenuNavigator = 'MenuNavigator',
  CartNavigator = 'CartNavigator',
  OrderType = 'OrderType',
  OrderAddress = 'OrderAddress',
  PersonalData = 'PersonalData',
  OrderDetails = 'OrderDetails',
  OrderPayment = 'OrderPayment',
  OrderConfirmation = 'OrderConfirmation',
  OrderIngredients = 'OrderIngredients',
  MenuDishToCart = 'MenuDishToCart',
  MenuBreakfast = 'MenuBreakfast',
  CartMain = 'CartMain',
  ProfileAddAddress = 'ProfileAddAddress',
  ProfileAddCard = 'ProfileAddCard',
  MenuMain = 'MenuMain',
  Home = 'Home',
  ProfileMain = 'ProfileMain',
  ProfileOrders = 'ProfileOrders',
  ProfileCards = 'ProfileCards',
  ProfileAddress = 'ProfileAddress',
}

export default ScreenNames;
